CAL_MODULE := WallDrops
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := walldrops.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true

